consume kafka events
Informasjonsforvaltning/fdk-sparql-service pull request #45
Opened 2024-01-31 07:43 UTC by NilsOveTen

2024-02-12 11:09 UTC, jeffreiffers requested changes

2024-02-12 11:09 UTC, jeffreiffers commented on pom.xml
> +        <avro.version>1.11.2</avro.version>
```suggestion
        <avro.version>1.11.3</avro.version>
```

2024-02-12 11:11 UTC, jeffreiffers commented on src/main/java/no/fdk/sparqlservice/kafka/KafkaEventConsumers.java
> +            groupId = "fdk-sparql-service",
Legg til concurrency=4

2024-02-13 11:50 UTC, NilsOveTen commented on pom.xml
> +        <avro.version>1.11.2</avro.version>
377f976

2024-02-13 11:50 UTC, NilsOveTen commented on src/main/java/no/fdk/sparqlservice/kafka/KafkaEventConsumers.java
> +            groupId = "fdk-sparql-service",
377f976

2024-02-13 13:22 UTC, jeffreiffers approved these changes

2024-02-13 15:06 UTC, pooriamehregan approved these changes

2024-02-14 07:34 UTC, merged